### ISSUE TITLE
Visual ARIA Bookmarklets transform with their associated elements

### ISSUE THREAD

**Issue by nodes777** [accdc/aria-matrices#6]
When elements are marked by Visual ARIA, if that element transforms with CSS, the descriptive marker also transforms. For example, for an element that is flipped vertically when activated, the text for the marker is also flipped vertically, making it harder to read.

- Taylor

**Comment by accdc** [comment]
Thanks, part of the challenge is that Visual ARIA is 99% CSS stylesheets, so these classes inherit from the base page when loaded. Are you aware of a CSS rule that would negate this? Also this code would need to be added to approximately 150 thousand classes within Visual ARIA.

**Comment by nodes777** [comment]
It's possible to use the [unset keyword](https://www.w3.org/TR/css3-values/#keywords) with the [all property](https://developer.mozilla.org/en/docs/Web/CSS/all) to do something like 

```
#someselector {
  all: initial;
  * {
    all: unset;
  }
}
```

Unfortunately, this is only supported in Chrome 37, Firefox 27, and Opera 24. So this doesn't seem like an appropriate fix. 

An alternative to that would be manually resetting all of the possible problematic CSS properties. Which is also a tedious process.

All is well, I just wanted to investigate this. Thanks!

**Comment by accdc** [comment]
No problem, experimentation is always good. Please feel free to download a copy of Visual ARIA in the archive at 
https://github.com/accdc/csun-2016
to try out some different variations within the class declarations if you wish. I'll be happy to add anything that helps.
